"""first migration

Revision ID: 81eaa7c150a2
Revises: 
Create Date: 2021-06-25 11:18:43.967744

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "81eaa7c150a2"
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "user",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("username", sa.String(length=20), nullable=False),
        sa.Column("email", sa.String(length=120), nullable=False),
        sa.Column("password", sa.String(length=60), nullable=False),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("email"),
        sa.UniqueConstraint("username"),
    )
    op.create_table(
        "products",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("user_id", sa.Integer(), nullable=False),
        sa.Column("product_name", sa.String(length=100), nullable=False),
        sa.Column("product_description", sa.String(length=550), nullable=True),
        sa.Column("category", sa.String(length=50), nullable=False),
        sa.Column("minimum_bid", sa.BigInteger(), nullable=False),
        sa.Column("post_created", sa.DateTime(), nullable=True),
        sa.Column("last_updated", sa.DateTime(), nullable=True),
        sa.Column("last_date_to_bid", sa.DateTime(), nullable=True),
        sa.Column("picture", sa.String(length=1600), nullable=False),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["user.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "bidder",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("bidders_id", sa.Integer(), nullable=False),
        sa.Column("product_id", sa.Integer(), nullable=False),
        sa.Column("bid_value", sa.DECIMAL(), nullable=False),
        sa.Column("note", sa.String(length=500), nullable=True),
        sa.ForeignKeyConstraint(
            ["product_id"],
            ["products.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("bidder")
    op.drop_table("products")
    op.drop_table("user")
    # ### end Alembic commands ###
